export type ProcessingMode = 'client' | 'server' | 'ai';
export type ToolStatus = 'active' | 'development' | 'planned';
export type ToolCategory = 'organize' | 'optimize' | 'convert' | 'edit' | 'security' | 'ai';

export interface PdfToolDefinition {
  id: string;
  slug: string;
  name: string;
  nameTH: string;
  description: string;
  category: ToolCategory;
  icon: string;
  route: string;
  status: ToolStatus;
  processingMode: ProcessingMode;
  maxFileSize: number; // in bytes (e.g. 50MB)
  maxFiles: number;
  isPremium: boolean;
  sortOrder: number;
  seoTitle: string;
  seoDescription: string;
  acceptedMimeTypes?: string[];
}

export interface CategoryInfo {
  id: ToolCategory;
  name: string;
  nameTH: string;
  description: string;
  icon: string;
}

export const PDF_CATEGORIES: CategoryInfo[] = [
  {
    id: 'organize',
    name: 'Organize PDF',
    nameTH: 'จัดระเบียบ PDF',
    description: 'รวม แยก หมุน และจัดการลำดับหน้าเอกสาร PDF ของคุณ',
    icon: 'Layers',
  },
  {
    id: 'optimize',
    name: 'Optimize PDF',
    nameTH: 'เพิ่มประสิทธิภาพ PDF',
    description: 'บีบอัด ซ่อมแซม และสแกน OCR เพื่อให้อ่านข้อความได้',
    icon: 'Zap',
  },
  {
    id: 'convert',
    name: 'Convert PDF',
    nameTH: 'แปลงไฟล์ PDF',
    description: 'แปลงไฟล์ระหว่าง PDF กับรูปภาพ เอกสาร Word, Excel, PowerPoint',
    icon: 'ArrowLeftRight',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    nameTH: 'แก้ไข PDF',
    description: 'เพิ่มข้อความ รูปภาพ ลายน้ำ เลขหน้า และฟอร์มกรอกข้อมูล',
    icon: 'PenTool',
  },
  {
    id: 'security',
    name: 'PDF Security',
    nameTH: 'ความปลอดภัย PDF',
    description: 'ล็อกรหัส ปลดล็อก เซ็นชื่อ ตรวจสอบ และเซ็นเซอร์ข้อความสำคัญ',
    icon: 'ShieldCheck',
  },
  {
    id: 'ai',
    name: 'AI PDF',
    nameTH: 'ระบบอัจฉริยะ AI PDF',
    description: 'สรุปเนื้อหา คุยกับเอกสาร แปลภาษา และแปลงเป็น Markdown',
    icon: 'Sparkles',
  },
];

export const PDF_TOOLS: PdfToolDefinition[] = [
  // ================= 1. ORGANIZE PDF =================
  {
    id: 'merge-pdf',
    slug: 'merge',
    name: 'Merge PDF',
    nameTH: 'รวมไฟล์ PDF',
    description: 'รวมเอกสาร PDF หลายไฟล์ให้เป็นไฟล์เดียวได้อย่างรวดเร็ว จัดลำดับได้ตามต้องการ',
    category: 'organize',
    icon: 'Combine',
    route: '/tools/pdf/merge',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 20,
    isPremium: false,
    sortOrder: 1,
    seoTitle: 'รวมไฟล์ PDF ออนไลน์ฟรี - จัดลำดับหน้าได้ง่าย รวดเร็ว ปลอดภัย | TOOL HUB',
    seoDescription: 'บริการรวม PDF ออนไลน์ฟรี รวมหลายเอกสารเป็นไฟล์เดียว รวดเร็ว ปลอดภัย ไม่ส่งข้อมูลขึ้นเซิร์ฟเวอร์',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'split-pdf',
    slug: 'split',
    name: 'Split PDF',
    nameTH: 'แยกไฟล์ PDF',
    description: 'แยกหน้า PDF ที่ต้องการ หรือแยกทุกหน้าออกเป็นไฟล์เดี่ยวได้อย่างง่ายดาย',
    category: 'organize',
    icon: 'Split',
    route: '/tools/pdf/split',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 2,
    seoTitle: 'แยกหน้า PDF ออนไลน์ฟรี - กำหนดช่วงหน้าได้อิสระ | TOOL HUB',
    seoDescription: 'แยกไฟล์ PDF ออกเป็นหลายไฟล์ตามช่วงหน้าที่เลือก รวดเร็ว ทำงานบนเบราว์เซอร์ 100%',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'remove-pages',
    slug: 'remove-pages',
    name: 'Remove Pages',
    nameTH: 'ลบหน้า PDF',
    description: 'เลือกลบหน้าที่ไม่ต้องการออกจากเอกสาร PDF อย่างแม่นยำด้วยการกดเลือกทีละหน้า',
    category: 'organize',
    icon: 'Trash2',
    route: '/tools/pdf/remove-pages',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 3,
    seoTitle: 'ลบหน้า PDF ที่ไม่ต้องการออนไลน์ - ปลอดภัย รวดเร็ว | TOOL HUB',
    seoDescription: 'เลือกลบหน้าที่ไม่ต้องการออกจากไฟล์ PDF ดาวน์โหลดเอกสารฉบับใหม่ได้ทันที',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'extract-pages',
    slug: 'extract-pages',
    name: 'Extract Pages',
    nameTH: 'แยกดึงหน้า PDF',
    description: 'เลือกเฉพาะหน้าที่ต้องการจากเอกสาร PDF เพื่อสร้างเป็นไฟล์ PDF เล่มใหม่',
    category: 'organize',
    icon: 'FileOutput',
    route: '/tools/pdf/extract-pages',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 4,
    seoTitle: 'ดึงหน้า PDF แยกไฟล์ใหม่ - ทำงานบนเว็บฟรี | TOOL HUB',
    seoDescription: 'ดึงเฉพาะหน้าที่สำคัญออกมาสร้างเป็นไฟล์ PDF ใหม่ ปลอดภัย ข้อมูลไม่รั่วไหล',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'organize-pdf',
    slug: 'organize',
    name: 'Organize PDF',
    nameTH: 'จัดเรียงหน้า PDF',
    description: 'ลากสลับตำแหน่งหน้า หมุน หรือลบหน้าในเอกสาร PDF ได้อย่างอิสระผ่านมุมมองตารางหน้า',
    category: 'organize',
    icon: 'Grid',
    route: '/tools/pdf/organize',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 5,
    seoTitle: 'จัดเรียงสลับหน้า PDF ออนไลน์ - สลับ ลบ หมุนหน้าในที่เดียว | TOOL HUB',
    seoDescription: 'จัดระเบียบหน้า PDF ลากสลับตำแหน่งหน้าตามใจชอบ ใช้งานง่ายบนมือถือและคอมพิวเตอร์',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'rotate-pdf',
    slug: 'rotate',
    name: 'Rotate PDF',
    nameTH: 'หมุนหน้า PDF',
    description: 'หมุนหน้าเอกสาร PDF ทุกหน้าหรือเฉพาะหน้าที่ต้องการ 90°, 180°, 270° ให้ถูกต้องตามแนวอ่าน',
    category: 'organize',
    icon: 'RotateCw',
    route: '/tools/pdf/rotate',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 6,
    seoTitle: 'หมุนหน้า PDF ออนไลน์ - หมุนแนวนอน แนวตั้ง 90 องศา | TOOL HUB',
    seoDescription: 'หมุนหน้า PDF ให้ตรงแนวอ่าน หมุนรายหน้าหรือหมุนทั้งเอกสารได้ง่ายๆ',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'scan-to-pdf',
    slug: 'scan-to-pdf',
    name: 'Scan to PDF',
    nameTH: 'สแกนเอกสารเป็น PDF',
    description: 'ใช้กล้องมือถือหรือเว็บแคมสแกนเอกสารจริงเป็นไฟล์ PDF',
    category: 'organize',
    icon: 'Scan',
    route: '/tools/pdf/scan-to-pdf',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 25 * 1024 * 1024,
    maxFiles: 10,
    isPremium: false,
    sortOrder: 7,
    seoTitle: 'สแกนเอกสารเป็น PDF | TOOL HUB',
    seoDescription: 'สแกนเอกสารจริงผ่านกล้องเป็น PDF',
  },

  // ================= 2. OPTIMIZE PDF =================
  {
    id: 'compress-pdf',
    slug: 'compress',
    name: 'Compress PDF',
    nameTH: 'บีบอัดลดขนาด PDF',
    description: 'ลดขนาดไฟล์ PDF ให้เล็กลงโดยยังคงความคมชัด เหมาะสำหรับการส่งอีเมลหรืออัปโหลด',
    category: 'optimize',
    icon: 'Minimize2',
    route: '/tools/pdf/compress',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 100 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 8,
    seoTitle: 'บีบอัด PDF ออนไลน์ - ลดขนาดไฟล์ PDF ฟรี | TOOL HUB',
    seoDescription: 'ลดขนาดไฟล์ PDF สำหรับส่งอีเมล คุณภาพชัดเจน ขนาดเล็กลงอย่างเห็นได้ชัด',
  },
  {
    id: 'repair-pdf',
    slug: 'repair',
    name: 'Repair PDF',
    nameTH: 'ซ่อมแซมไฟล์ PDF',
    description: 'กู้คืนและซ่อมแซมโครงสร้างเอกสาร PDF ที่เสียหายหรือเปิดไม่ได้',
    category: 'optimize',
    icon: 'Wrench',
    route: '/tools/pdf/repair',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 9,
    seoTitle: 'ซ่อมไฟล์ PDF ที่เสียหาย | TOOL HUB',
    seoDescription: 'กู้คืนและซ่อมแซมโครงสร้างเอกสาร PDF ที่เสียหาย',
  },
  {
    id: 'ocr-pdf',
    slug: 'ocr',
    name: 'OCR PDF',
    nameTH: 'แปลงภาพ PDF เป็นข้อความ (OCR)',
    description: 'ตรวจจับตัวอักษรในไฟล์สแกน PDF เพื่อให้สามารถค้นหา คัดลอก และแก้ไขข้อความได้',
    category: 'optimize',
    icon: 'FileSearch',
    route: '/tools/pdf/ocr',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 10,
    seoTitle: 'OCR PDF แปลงภาพเป็นตัวหนังสือไทยและอังกฤษ | TOOL HUB',
    seoDescription: 'ระบบตรวจจับข้อความ OCR แม่นยำสูง รองรับภาษาไทยและภาษาอังกฤษ',
  },

  // ================= 3. CONVERT PDF =================
  {
    id: 'jpg-to-pdf',
    slug: 'jpg-to-pdf',
    name: 'JPG to PDF',
    nameTH: 'แปลง JPG เป็น PDF',
    description: 'แปลงรูปภาพ JPG, JPEG, PNG หลายรูปให้เป็นเอกสาร PDF รวมเล่มอย่างสวยงาม',
    category: 'convert',
    icon: 'Image',
    route: '/tools/pdf/jpg-to-pdf',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 25 * 1024 * 1024,
    maxFiles: 30,
    isPremium: false,
    sortOrder: 11,
    seoTitle: 'แปลงรูปภาพ JPG เป็น PDF รวมเล่มฟรี | TOOL HUB',
    seoDescription: 'แปลงไฟล์ JPG/PNG เป็น PDF ปรับขนาดหน้า จัดเรียงรูปภาพได้ตามใจชอบ',
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
  },
  {
    id: 'pdf-to-jpg',
    slug: 'pdf-to-jpg',
    name: 'PDF to JPG',
    nameTH: 'แปลง PDF เป็น JPG',
    description: 'แปลงหน้าเอกสาร PDF ทุกหน้าหรือหน้าที่เลือกให้เป็นรูปภาพ JPG คุณภาพสูง',
    category: 'convert',
    icon: 'FileImage',
    route: '/tools/pdf/pdf-to-jpg',
    status: 'active',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 12,
    seoTitle: 'แปลงไฟล์ PDF เป็นภาพ JPG คมชัดสูง | TOOL HUB',
    seoDescription: 'แยกหน้า PDF เป็นไฟล์รูปภาพ JPG ดาวน์โหลดเป็นไฟล์เดี่ยวหรือไฟล์ ZIP ได้ทันที',
    acceptedMimeTypes: ['application/pdf'],
  },
  {
    id: 'png-to-pdf',
    slug: 'png-to-pdf',
    name: 'PNG to PDF',
    nameTH: 'แปลง PNG เป็น PDF',
    description: 'แปลงไฟล์ภาพ PNG ความโปร่งใสสูงเป็นไฟล์ PDF',
    category: 'convert',
    icon: 'ImagePlus',
    route: '/tools/pdf/png-to-pdf',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 25 * 1024 * 1024,
    maxFiles: 30,
    isPremium: false,
    sortOrder: 13,
    seoTitle: 'แปลง PNG เป็น PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'แปลงไฟล์ PNG เป็น PDF สะดวกรวดเร็ว',
  },
  {
    id: 'word-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word to PDF',
    nameTH: 'แปลง Word เป็น PDF',
    description: 'แปลงเอกสาร DOCX และ DOC ให้เป็น PDF คงรูปแบบตัวอักษรและตารางครบถ้วน',
    category: 'convert',
    icon: 'FileText',
    route: '/tools/pdf/word-to-pdf',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 14,
    seoTitle: 'แปลงไฟล์ Word เป็น PDF ออนไลน์ ฟอนต์ไม่เพี้ยน | TOOL HUB',
    seoDescription: 'แปลง DOC, DOCX เป็น PDF คุณภาพสูง สวยงามตรงตามต้นฉบับ',
  },
  {
    id: 'pdf-to-word',
    slug: 'pdf-to-word',
    name: 'PDF to Word',
    nameTH: 'แปลง PDF เป็น Word',
    description: 'แปลงเอกสาร PDF เป็นไฟล์ DOCX ที่สามารถเปิดแก้ไขข้อความและตารางใน Word ได้',
    category: 'convert',
    icon: 'FileType',
    route: '/tools/pdf/pdf-to-word',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 15,
    seoTitle: 'แปลง PDF เป็น Word แก้ไขได้ ฟอนต์ตรง | TOOL HUB',
    seoDescription: 'แปลงเอกสาร PDF กลับเป็น Word เพื่อแก้ไขข้อความและจัดหน้าใหม่',
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel to PDF',
    nameTH: 'แปลง Excel เป็น PDF',
    description: 'แปลงสเปรดชีต XLSX, XLS ให้เป็นตาราง PDF ที่จัดหน้ากระดาษอย่างเป็นระเบียบ',
    category: 'convert',
    icon: 'Sheet',
    route: '/tools/pdf/excel-to-pdf',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 16,
    seoTitle: 'แปลง Excel เป็น PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'แปลงไฟล์ Excel เป็น PDF คงความถูกต้องของสูตรและตาราง',
  },
  {
    id: 'pdf-to-excel',
    slug: 'pdf-to-excel',
    name: 'PDF to Excel',
    nameTH: 'แปลง PDF เป็น Excel',
    description: 'ดึงตารางข้อมูลจากเอกสาร PDF ออกมาเป็นชีต Excel (XLSX) เพื่อนำไปคำนวณต่อ',
    category: 'convert',
    icon: 'Table',
    route: '/tools/pdf/pdf-to-excel',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 17,
    seoTitle: 'แปลงตาราง PDF เป็น Excel XLSX ออนไลน์ | TOOL HUB',
    seoDescription: 'ดึงตารางจาก PDF ออกมาเป็น Excel สะดวกต่อการวิเคราะห์ข้อมูล',
  },
  {
    id: 'powerpoint-to-pdf',
    slug: 'powerpoint-to-pdf',
    name: 'PowerPoint to PDF',
    nameTH: 'แปลง PowerPoint เป็น PDF',
    description: 'แปลงสไลด์งานนำเสนอ PPTX เป็นเอกสาร PDF พร้อมสำหรับเปิดฉายหรือแจกจ่าย',
    category: 'convert',
    icon: 'Presentation',
    route: '/tools/pdf/powerpoint-to-pdf',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 18,
    seoTitle: 'แปลง PowerPoint PPTX เป็น PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'แปลงงานนำเสนอเป็น PDF คุณภาพสูง สไลด์คมชัด',
  },
  {
    id: 'pdf-to-powerpoint',
    slug: 'pdf-to-powerpoint',
    name: 'PDF to PowerPoint',
    nameTH: 'แปลง PDF เป็น PowerPoint',
    description: 'แปลงไฟล์ PDF กลับเป็นสไลด์ PPTX เพื่อนำไปนำเสนอหรือแก้ไขต่อ',
    category: 'convert',
    icon: 'MonitorPlay',
    route: '/tools/pdf/pdf-to-powerpoint',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 19,
    seoTitle: 'แปลง PDF เป็น PowerPoint PPTX | TOOL HUB',
    seoDescription: 'แปลง PDF เป็นสไลด์นำเสนอได้อย่างง่ายดาย',
  },
  {
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    nameTH: 'แปลงเว็บ/HTML เป็น PDF',
    description: 'บันทึกหน้าเว็บ URL หรือโค้ด HTML ให้ออกมาเป็นไฟล์เอกสาร PDF',
    category: 'convert',
    icon: 'Globe',
    route: '/tools/pdf/html-to-pdf',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 10 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 20,
    seoTitle: 'แปลงหน้าเว็บ HTML เป็น PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'บันทึกหน้าเว็บเป็นเอกสาร PDF เก็บไว้อ่านออฟไลน์',
  },
  {
    id: 'pdf-to-pdfa',
    slug: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    nameTH: 'แปลง PDF เป็น PDF/A',
    description: 'แปลงเอกสาร PDF ให้เป็นมาตรฐาน PDF/A สำหรับการจัดเก็บเอกสารระยะยาวตามกฎหมาย',
    category: 'convert',
    icon: 'Archive',
    route: '/tools/pdf/pdf-to-pdfa',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 21,
    seoTitle: 'แปลง PDF เป็นมาตรฐาน PDF/A สำหรับจัดเก็บเอกสารราชการ | TOOL HUB',
    seoDescription: 'แปลงไฟล์เป็น PDF/A สำหรับการเก็บถาวรระยะยาว',
  },

  // ================= 4. EDIT PDF =================
  {
    id: 'add-text',
    slug: 'add-text',
    name: 'Add Text',
    nameTH: 'พิมพ์ข้อความลงใน PDF',
    description: 'พิมพ์ข้อความ เติมคำในช่องว่าง ปรับแต่งขนาด สี และฟอนต์ลงในหน้า PDF',
    category: 'edit',
    icon: 'Type',
    route: '/tools/pdf/add-text',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 22,
    seoTitle: 'เพิ่มข้อความลงใน PDF ออนไลน์ฟรี | TOOL HUB',
    seoDescription: 'กรอกข้อความ พิมพ์ข้อความภาษาไทยลงบน PDF ได้โดยตรง',
  },
  {
    id: 'add-image',
    slug: 'add-image',
    name: 'Add Image',
    nameTH: 'แทรกรูปลงใน PDF',
    description: 'แทรกรูปภาพ ตรายาง ตราประทับ ลงในตำแหน่งที่ต้องการของหน้า PDF',
    category: 'edit',
    icon: 'Image',
    route: '/tools/pdf/add-image',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 23,
    seoTitle: 'แทรกรูปลงในเอกสาร PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'แทรกรูปภาพ ตรายาง หรือโลโก้ลงในหน้า PDF',
  },
  {
    id: 'page-numbers',
    slug: 'page-numbers',
    name: 'Page Numbers',
    nameTH: 'ใส่เลขหน้า PDF',
    description: 'ใส่หมายเลขหน้าลงในเอกสาร PDF เลือกตำแหน่ง หัวกระดาษ ท้ายกระดาษ รูปแบบตัวเลขได้',
    category: 'edit',
    icon: 'Hash',
    route: '/tools/pdf/page-numbers',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 24,
    seoTitle: 'ใส่เลขหน้า PDF ออนไลน์ฟรี ปรับแต่งตำแหน่งได้ | TOOL HUB',
    seoDescription: 'รันหมายเลขหน้าในเอกสาร PDF จัดวางตำแหน่งบน ล่าง ซ้าย ขวา กึ่งกลางได้อิสระ',
  },
  {
    id: 'watermark',
    slug: 'watermark',
    name: 'Watermark',
    nameTH: 'ใส่ลายน้ำ PDF',
    description: 'เพิ่มลายน้ำข้อความหรือโลโก้รูปภาพ ปรับความโปร่งแสง มุมเอียง และขนาดเพื่อกันการคัดลอก',
    category: 'edit',
    icon: 'Stamp',
    route: '/tools/pdf/watermark',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 25,
    seoTitle: 'ใส่ลายน้ำ PDF ออนไลน์ - ป้องกันการคัดลอกเอกสาร | TOOL HUB',
    seoDescription: 'เพิ่มข้อความลายน้ำหรือรูปภาพโลโก้ลงบนเอกสาร PDF',
  },
  {
    id: 'crop-pdf',
    slug: 'crop',
    name: 'Crop PDF',
    nameTH: 'ครอบตัดขอบ PDF',
    description: 'ตัดขอบขาวส่วนเกินของเอกสาร PDF ปรับขนาดหน้ากระดาษให้กระชับพอดี',
    category: 'edit',
    icon: 'Crop',
    route: '/tools/pdf/crop',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 26,
    seoTitle: 'ครอบตัดขอบ PDF ตัดขอบขาวส่วนเกินออนไลน์ | TOOL HUB',
    seoDescription: 'Crop หน้า PDF ให้พอดีเนื้อหา ตัดขอบกระดาษส่วนเกินออก',
  },
  {
    id: 'pdf-forms',
    slug: 'forms',
    name: 'PDF Forms',
    nameTH: 'กรอกฟอร์ม PDF',
    description: 'เปิดกรอกแบบฟอร์ม PDF แบบ Interactive ติ๊กถูก กรอกข้อความ และบันทึกผล',
    category: 'edit',
    icon: 'CheckSquare',
    route: '/tools/pdf/forms',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 27,
    seoTitle: 'กรอกแบบฟอร์ม PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'กรอกข้อมูลลงในช่องฟอร์ม PDF และบันทึกส่งต่อได้ทันที',
  },

  // ================= 5. PDF SECURITY =================
  {
    id: 'protect-pdf',
    slug: 'protect',
    name: 'Protect PDF',
    nameTH: 'ล็อกรหัสผ่าน PDF',
    description: 'ตั้งรหัสผ่านเข้ารหัสเอกสาร PDF ป้องกันไม่ให้ผู้อื่นเปิดอ่านโดยไม่ได้รับอนุญาต',
    category: 'security',
    icon: 'Lock',
    route: '/tools/pdf/protect',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 28,
    seoTitle: 'ตั้งรหัสผ่านล็อกไฟล์ PDF ออนไลน์ ปลอดภัยสูง | TOOL HUB',
    seoDescription: 'ใส่ Password ป้องกันการเปิดเอกสาร PDF ด้วยการเข้ารหัสมาตรฐาน',
  },
  {
    id: 'unlock-pdf',
    slug: 'unlock',
    name: 'Unlock PDF',
    nameTH: 'ปลดล็อกรหัสผ่าน PDF',
    description: 'ปลดล็อกและลบรหัสผ่านออกจากไฟล์ PDF เพื่อให้เปิดอ่านได้โดยไม่ต้องกรอกรหัสซ้ำ',
    category: 'security',
    icon: 'Unlock',
    route: '/tools/pdf/unlock',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 29,
    seoTitle: 'ปลดล็อกรหัสผ่าน PDF ออนไลน์ | TOOL HUB',
    seoDescription: 'ลบรหัสผ่านออกจากเอกสาร PDF ให้เปิดอ่านได้สะดวก',
  },
  {
    id: 'sign-pdf',
    slug: 'sign',
    name: 'Sign PDF',
    nameTH: 'เซ็นลายเซ็นอิเล็กทรอนิกส์',
    description: 'วาดลายเซ็น อัปโหลดรูปภาพลายเซ็น หรือพิมพ์ชื่อเพื่อลงนามในเอกสาร PDF',
    category: 'security',
    icon: 'FileSignature',
    route: '/tools/pdf/sign',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 30,
    seoTitle: 'เซ็นชื่อใน PDF ออนไลน์ฟรี ลงลายเซ็นอิเล็กทรอนิกส์ | TOOL HUB',
    seoDescription: 'วาดหรือแนบลายเซ็นลงบนสัญญาและเอกสาร PDF ได้อย่างรวดเร็ว',
  },
  {
    id: 'redact-pdf',
    slug: 'redact',
    name: 'Redact PDF',
    nameTH: 'เซ็นเซอร์ปิดข้อมูลลับ',
    description: 'ถมดำปิดทับข้อมูลส่วนบุคคล เลขบัตรประชาชน หรือข้อมูลสำคัญที่ไม่อยากเปิดเผย',
    category: 'security',
    icon: 'EyeOff',
    route: '/tools/pdf/redact',
    status: 'development',
    processingMode: 'client',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 31,
    seoTitle: 'เซ็นเซอร์ปิดบังข้อความลับใน PDF ถมดำข้อมูลสำคัญ | TOOL HUB',
    seoDescription: 'ลบและเซ็นเซอร์ข้อมูลส่วนบุคคลออกจากเอกสาร PDF อย่างถาวร',
  },
  {
    id: 'compare-pdf',
    slug: 'compare',
    name: 'Compare PDF',
    nameTH: 'เปรียบเทียบเอกสาร PDF',
    description: 'เปรียบเทียบความแตกต่างระหว่างไฟล์ PDF 2 ฉบับ ไฮไลต์จุดที่มีการแก้ไข',
    category: 'security',
    icon: 'Columns2',
    route: '/tools/pdf/compare',
    status: 'development',
    processingMode: 'server',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 2,
    isPremium: true,
    sortOrder: 32,
    seoTitle: 'เปรียบเทียบความแตกต่างของไฟล์ PDF 2 ไฟล์ | TOOL HUB',
    seoDescription: 'ตรวจหาจุดต่างและการแก้ไขระหว่างเอกสาร 2 ฉบับอย่างแม่นยำ',
  },

  // ================= 6. AI PDF =================
  {
    id: 'summarize-pdf',
    slug: 'summarize',
    name: 'Summarize PDF',
    nameTH: 'สรุปเนื้อหา PDF ด้วย AI',
    description: 'ใช้ AI วิเคราะห์และสรุปประเด็นสำคัญของรายงาน หนังสือ หรือวิทยานิพนธ์เป็นภาษาไทย',
    category: 'ai',
    icon: 'Bot',
    route: '/tools/pdf/summarize',
    status: 'development',
    processingMode: 'ai',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 33,
    seoTitle: 'สรุป PDF ด้วย AI ภาษาไทย สรุปเนื้อหาสำคัญแม่นยำ | TOOL HUB',
    seoDescription: 'วิเคราะห์และสรุปย่อเนื้อหาเอกสาร PDF ยาวๆ ภายในไม่กี่วินาที',
  },
  {
    id: 'ask-pdf',
    slug: 'ask',
    name: 'Ask PDF',
    nameTH: 'แชทคุยกับ PDF (Q&A)',
    description: 'พิมพ์คำถามเพื่อหาคำตอบจากเอกสาร PDF โดยตรง พร้อมอ้างอิงเลขหน้าที่พบข้อมูล',
    category: 'ai',
    icon: 'MessageSquareText',
    route: '/tools/pdf/ask',
    status: 'development',
    processingMode: 'ai',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 34,
    seoTitle: 'แชทถาม-ตอบกับเอกสาร PDF ด้วย AI | TOOL HUB',
    seoDescription: 'พิมพ์ถามสิ่งที่อยากรู้จากเนื้อหาใน PDF ค้นหาข้อมูลได้ทันที',
  },
  {
    id: 'translate-pdf',
    slug: 'translate',
    name: 'Translate PDF',
    nameTH: 'แปลภาษา PDF',
    description: 'แปลภาษาเอกสาร PDF ทั้งเล่ม คงโครงสร้างและรูปแบบหน้าเดิมไว้อย่างสวยงาม',
    category: 'ai',
    icon: 'Languages',
    route: '/tools/pdf/translate',
    status: 'development',
    processingMode: 'ai',
    maxFileSize: 50 * 1024 * 1024,
    maxFiles: 1,
    isPremium: true,
    sortOrder: 35,
    seoTitle: 'แปลเอกสาร PDF ภาษาอังกฤษเป็นไทย คงรูปเล่มเดิม | TOOL HUB',
    seoDescription: 'แปลภาษาเอกสาร PDF ทั้งฉบับด้วย AI จัดหน้าสวยงามเหมือนต้นฉบับ',
  },
  {
    id: 'pdf-to-markdown',
    slug: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    nameTH: 'แปลง PDF เป็น Markdown',
    description: 'แปลงเนื้อหา PDF เป็นรูปแบบ Markdown (.md) สำหรับนำไปใช้กับ LLM, Notion หรือ Obsidian',
    category: 'ai',
    icon: 'FileCode2',
    route: '/tools/pdf/pdf-to-markdown',
    status: 'development',
    processingMode: 'ai',
    maxFileSize: 25 * 1024 * 1024,
    maxFiles: 1,
    isPremium: false,
    sortOrder: 36,
    seoTitle: 'แปลง PDF เป็น Markdown (MD) ออนไลน์ | TOOL HUB',
    seoDescription: 'แปลงเอกสาร PDF เป็น Markdown สะอาด พร้อมใช้งานกับ AI และ Note App',
  },
];

export function getToolBySlug(slug: string): PdfToolDefinition | undefined {
  return PDF_TOOLS.find((tool) => tool.slug === slug);
}

export function getActiveTools(): PdfToolDefinition[] {
  return PDF_TOOLS.filter((tool) => tool.status === 'active');
}

export function getToolsByCategory(category: ToolCategory): PdfToolDefinition[] {
  return PDF_TOOLS.filter((tool) => tool.category === category);
}
